# Generated by Django 5.2.9 on 2025-12-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидается', 'ожидается'), ('выдан', 'выдан')], default='ожидается', max_length=20),
        ),
    ]
