# Generated by Django 5.2.9 on 2025-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
