# Generated by Django 5.2.9 on 2026-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Подробное описание блюда', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото блюда', null=True, upload_to='menu_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Краткое название блюда', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stock',
            field=models.IntegerField(default=0, help_text='Количество доступных порций', verbose_name='Остаток'),
        ),
    ]
