# Generated by Django 5.2.3 on 2026-04-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='orders.menuitem', verbose_name='Избранное'),
        ),
    ]
