# Generated by Django 5.2.3 on 2026-04-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время получения'),
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateTimeField(verbose_name='Время получения')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
            },
        ),
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem')),
                ('pre_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.preorder')),
            ],
            options={
                'verbose_name': 'Позиция предзаказа',
                'verbose_name_plural': 'Позиции предзаказов',
            },
        ),
        migrations.AddField(
            model_name='preorder',
            name='menu_items',
            field=models.ManyToManyField(through='orders.PreOrderItem', to='orders.menuitem'),
        ),
    ]
