# Generated by Django 5.2.3 on 2026-04-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_pickup_time_preorder_preorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
