# Generated by Django 5.2.3 on 2026-04-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('low_stock', 'Мало товара на складе'), ('out_of_stock', 'Товар закончился'), ('quality_issue', 'Проблема с качеством'), ('pricing_error', 'Ошибка в цене'), ('menu_update', 'Обновление меню'), ('other', 'Другое')], max_length=20, verbose_name='Тип отчёта')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки администратора')),
                ('admin', models.ForeignKey(limit_choices_to={'user_type': 'canteen_admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
