# Generated by Django 5.2.3 on 2026-04-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('canteen_admin', 'Canteen Admin'), ('db_admin', 'DB Admin'), ('tech_support', 'Tech Support')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('category', models.CharField(choices=[('technical', 'Техническая проблема'), ('payment', 'Проблема с оплатой'), ('order', 'Проблема с заказом'), ('account', 'Проблема с аккаунтом'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('answered', 'Отвечен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус')),
                ('support_response', models.TextField(blank=True, null=True, verbose_name='Ответ поддержки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('support_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник поддержки')),
            ],
            options={
                'verbose_name': 'Запрос в поддержку',
                'verbose_name_plural': 'Запросы в поддержку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
