# Generated by Django 5.2.3 on 2026-05-12 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.IntegerField(default=0, verbose_name='Количество заказов')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Общее количество')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Популярное блюдо',
                'verbose_name_plural': 'Популярные блюда',
                'unique_together': {('menu_item',)},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Оценка релевантности')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem', verbose_name='Рекомендуемое блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-score'],
                'unique_together': {('user', 'menu_item')},
            },
        ),
    ]
